use_frameworks!

target 'TableViewArray_Example' do
  pod 'TableViewArray/TableViewArray', :path => '../'
  pod 'TableViewArray/Category', :path => '../'

  target 'TableViewArray_Tests' do
    inherit! :search_paths
  end
end
